### ISSUE TITLE
This project is dead?

### ISSUE THREAD

**Issue by ghost** [jquesnelle/nds4droid#13]
It's been 3 years since the last update 🤷

**Comment by Nintendo365** [comment]
Ik. But I think they should continue.

**Comment by ghost** [comment]
Drastic will soon become open source :)

**Comment by ghost** [comment]
melonDS for android is much better than this
https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.7.0

**Comment by ghost** [comment]
@jquesnelle still hoping you can continue this project :)
